# Generated by Django 5.0.7 on 2024-08-06 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='open_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
