# Generated by Django 5.0.7 on 2024-08-06 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_lesson_description_alter_lesson_open_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='open_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
