# Generated by Django 5.0.7 on 2024-08-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_studentquiz_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='success_threshold',
            field=models.IntegerField(default=50),
        ),
    ]
