# Generated by Django 5.0.7 on 2024-08-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_quiz_success_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
