# Generated by Django 5.0.7 on 2024-08-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_quiz_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquiz',
            name='status',
            field=models.CharField(blank=True, choices=[('passed', 'Passed'), ('failed', 'Failed')], max_length=10, null=True),
        ),
    ]
