# Generated by Django 5.0.7 on 2024-08-09 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_completion_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
